version: '3'

services:
  nginx:
    image: nginx
    ports:
    - 8090:80
    volumes:
    - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    - ./nginx/logs/:/var/log/nginx

  webapi:
    build:
      dockerfile: ./WebAPI/Dockerfile
      context: ../../Backend
      args:
        BUILD_CONFIGURATION: Debug
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - App__ApiUrls__UrlWebApi2=http://webapi2:8080/internal-api/

  webapi2:
    build:
      dockerfile: ./WebAPI2/Dockerfile
      context: ../../Backend
      args:
        BUILD_CONFIGURATION: Debug
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  front:
    build:
      context: ../../Front
      dockerfile: Dockerfile

